; Script generated by Inno Setup Script Wizard for CCTV Health Monitoring System
#define MyAppName "CCTV Health Monitoring System"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "Surveillance Infrastructure Team"
#define MyAppURL "http://localhost:8000"
#define MyAppExeName "CCTV-Health-Monitor.exe"
#define MyAppAssocName MyAppName + " File"
#define MyAppAssocExt ".cctv"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
AppId={{8B5C7D29-5E91-447F-A8C3-D5C68A019E01}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\CCTV Health Monitor
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
; Choose icon for setup installer
SetupIconFile=app_icon.ico
UninstallDisplayIcon={app}\{#MyAppExeName}
OutputDir=installer_output
OutputBaseFilename=CCTV_Health_Monitor_Setup_v1.0.0
Compression=lzma2/ultra64
SolidCompression=yes
WizardStyle=modern
; Allow installation for current user or all users (Win 10 & Win 11)
PrivilegesRequiredOverridesAllowed=commandline dialog
ArchitecturesInstallIn64BitMode=x64compatible
DisableWelcomePage=no

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "autostart"; Description: "Automatically start CCTV Health Monitor when Windows boots"; GroupDescription: "System Services:"

[Files]
Source: "dist\CCTV-Health-Monitor\*"; DestDir: "{app}"; Excludes: "*.db,*.db-shm,*.db-wal,*.log"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; IconFilename: "{app}\{#MyAppExeName}"
Name: "{group}\Open Web Dashboard"; Filename: "http://localhost:8085"
Name: "{group}\Snapshots Folder"; Filename: "{app}\static\snapshots"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon; IconFilename: "{app}\{#MyAppExeName}"

[Registry]
; Optional autostart on Windows boot if task was selected
Root: HKCU; Subkey: "Software\Microsoft\Windows\CurrentVersion\Run"; ValueType: string; ValueName: "CCTVHealthMonitor"; ValueData: """{app}\{#MyAppExeName}"""; Flags: uninsdeletevalue; Tasks: autostart

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent
